- index.ts
- models/types.ts
- package-lock.json
- package.json
hydrogen is not going to be used, GP does not have AnnualFuelConsumption so we have to figure out what to use instead
> update TEA, require selection of type

- index.ts
- package.json
- processYear.ts
> use the function from lca npm package to get lca results

- index.ts
- processYear.ts
> fix lca function

- package.json
- processDistance.ts
- processYear.ts
Found several issues when checking the algorithm, including
- whether or not to update the move-in distance has nothing to do with forest treatment
- only when treatment is biomass salvage, should all trees be chipped (`ChipAll = true`)
- the first year is 2016 based on our current setting instead of 2020
- fix total biomass/feedstock cost calculation 
Also added some comments and restructured the code a bit
> Fix the algorithm for processYear

- processDistance.ts
in some cases clusters are grouped tightly such that a chunk can have too many clusters for a realistic route calculation.  Loop and reduce bias until we don't have any more oversized clusters.
> ensure no cluster has more than N elements in it

- models/types.ts
- processDistance.ts
- processYear.ts
- runSupplyCurve.ts
To avoid confusion, refactor `totalFeedstockCost` to `totalHarvestCost`. 
`totalHarvestCost` is supposed to be part of `totalFeedstockCost`
> refactor totalFeedstockCost to totalHarvestCost

- runFacilitySupplyCurves.ts
will take a long time!  currently skips the 1 system that requires move-in calculations.
> runs all possibly supply curves for one facility

- processYear.ts
Reverts ucdavis/cecdss-backend#56
> Revert "use circular radius instead of square"

- frcsInputCalculations.ts
> set ChipAll to true only when forest treatment is biomass salvage

- processYear.ts
Added some comments to `processYear` sort out the algorithm.
For ucdavis/cecdss#159, after much investigation, I think the problem is that our algorithm does not have a proper terminating condition. The app did not enter an infinite loop but the front end never got back from the backend the results of the first year. I tried running the app locally on my desktop with the same inputs, and my desktop ended up crashing.
> Investigate the issue associated with Timber Salvage

- models/treatedcluster.ts
- processDistance.ts
- processYear.ts
what's in the database is `county_name`
> rename county to county_name

- index.ts
- processDistance.ts
- processYear.ts
just going to merge so I can get to upgrading dependencies
> remove some of the less useful logging

- index.ts
- package-lock.json
- package.json
looking to determine what takes so long for app to run a year.
> add in app insights for performance analytics

- processYear.ts
ucdavis/cecdss#162 A rough optimization by simply increasing the searching area. No guarantee that such an implementation would get us the most cost-efficient feedstock but it should be better than the current implementation. Although it will incur more computations, thus a longer running time, but it is worth a try.
> Optimize feedstock collection

- processYear.ts
Reverts ucdavis/cecdss-backend#87
> Revert "Optimize feedstock collection"

- processYear.ts
> increase feedstock searching area by doubling biomass target

- processYear.ts
Reverts ucdavis/cecdss-backend#90
> Revert "increase feedstock searching area by doubling biomass target"

- processYear.ts
hopefully this will spread out the osrm startup time and allow better cpu usage
> process all clusters in parallel

- index.ts
- package-lock.json
- package.json
- swagger.json
so we at least have something on the index page
> add starter swagger file

- frcsInputCalculations.ts
- index.ts
- models/ProcessedTreatedCluster.ts
- models/types.ts
- package-lock.json
- package.json
- processDistance.ts
- processYear.ts
- runFacilitySupplyCurves.ts
- runFrcs.ts
- runSupplyCurve.ts
The new version of frcs npm added new inputs, renamed variables, input model, and output model. It also changed folder structure
> Update frcs npm to v1.2.1

- swagger.json
document process and processRoutes endpoints
> swagger for the other two methods

- index.ts
this way instead of our callers getting nothing back on errors they'll get back 500 status codes.
Can be augmented in the future to send different status codes depending on the type of error if we so desire.
> set 5 min timeout and wrap methods in try/catch

- models/ProcessedTreatedCluster.ts
- models/types.ts
- package-lock.json
- package.json
- processDistance.ts
- processYear.ts
- Change `diesel` to `harvestDiesel` and compute `unloadDiesel`
- The new package attributes the unloading emissions to feedstock transport stage
> Use @ucdavis/lca v1.6.4

- .dockerignore
- .github/workflows/web-publish.yml
- Dockerfile
- forestry.lua
Build OSRM as part of the docker build process, then copy over the resulting /data/ files into the final container.  then add a github workflow to build and deploy the container when master branch changes
> Create dockerfile and workflow for building

- WIKI.md
- index.ts
- package-lock.json
- processDistance.ts
- processYear.ts
- runFrcs.ts
- Sanitizing the FRCS output which has NaN values due to the data. Cluster processing fails because of this.
- Added the WIKI.md file
> Sanitizing FRCS Output and uncommenting stuff.
